import type { AuthenticatedUser } from "../../common/decorators/current-user.decorator";
import { InvoicesService } from "./invoices.service";
import { CreateInvoiceDto, UpdateInvoiceDto } from "./dto/create-invoice.dto";
export declare class InvoicesController {
    private readonly invoicesService;
    constructor(invoicesService: InvoicesService);
    list(user: AuthenticatedUser): Promise<{
        data: ({
            contact: {
                id: string;
                tenantId: string;
                email: string;
                name: string;
                createdAt: Date;
                updatedAt: Date;
                phone: string | null;
                companyName: string | null;
                metadata: import("@sealed/database/generated/client/runtime/library").JsonValue;
            };
            agreement: {
                id: string;
                tenantId: string;
                status: import("@sealed/database").$Enums.AgreementStatus;
                createdAt: Date;
                updatedAt: Date;
                signatureProvider: string | null;
                contactId: string;
                publicToken: string;
                title: string;
                sentAt: Date | null;
                createdByUserId: string;
                proposalId: string;
                body: string;
                signatureRequestId: string | null;
                signedDocumentUrl: string | null;
                signerName: string | null;
                signerEmail: string | null;
                signerIpAddress: string | null;
                signedAt: Date | null;
                declinedAt: Date | null;
            };
        } & {
            number: string;
            id: string;
            tenantId: string;
            status: import("@sealed/database").$Enums.InvoiceStatus;
            createdAt: Date;
            updatedAt: Date;
            contactId: string;
            publicToken: string;
            lineItems: import("@sealed/database/generated/client/runtime/library").JsonValue;
            subtotal: import("@sealed/database/generated/client/runtime/library").Decimal;
            taxAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            totalAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            currency: string;
            sentAt: Date | null;
            createdByUserId: string;
            agreementId: string;
            amountPaid: import("@sealed/database/generated/client/runtime/library").Decimal;
            issueDate: Date;
            dueDate: Date | null;
            stripePaymentLinkUrl: string | null;
            stripePaymentLinkId: string | null;
            paidAt: Date | null;
            voidedAt: Date | null;
        })[];
    }>;
    getOne(user: AuthenticatedUser, id: string): Promise<{
        data: {
            contact: {
                id: string;
                tenantId: string;
                email: string;
                name: string;
                createdAt: Date;
                updatedAt: Date;
                phone: string | null;
                companyName: string | null;
                metadata: import("@sealed/database/generated/client/runtime/library").JsonValue;
            };
            agreement: {
                id: string;
                tenantId: string;
                status: import("@sealed/database").$Enums.AgreementStatus;
                createdAt: Date;
                updatedAt: Date;
                signatureProvider: string | null;
                contactId: string;
                publicToken: string;
                title: string;
                sentAt: Date | null;
                createdByUserId: string;
                proposalId: string;
                body: string;
                signatureRequestId: string | null;
                signedDocumentUrl: string | null;
                signerName: string | null;
                signerEmail: string | null;
                signerIpAddress: string | null;
                signedAt: Date | null;
                declinedAt: Date | null;
            };
            payments: {
                id: string;
                tenantId: string;
                status: import("@sealed/database").$Enums.PaymentStatus;
                createdAt: Date;
                currency: string;
                invoiceId: string;
                provider: import("@sealed/database").$Enums.PaymentProvider;
                providerPaymentId: string | null;
                amount: import("@sealed/database/generated/client/runtime/library").Decimal;
                succeededAt: Date | null;
                failedAt: Date | null;
                refundedAt: Date | null;
                failureReason: string | null;
            }[];
        } & {
            number: string;
            id: string;
            tenantId: string;
            status: import("@sealed/database").$Enums.InvoiceStatus;
            createdAt: Date;
            updatedAt: Date;
            contactId: string;
            publicToken: string;
            lineItems: import("@sealed/database/generated/client/runtime/library").JsonValue;
            subtotal: import("@sealed/database/generated/client/runtime/library").Decimal;
            taxAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            totalAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            currency: string;
            sentAt: Date | null;
            createdByUserId: string;
            agreementId: string;
            amountPaid: import("@sealed/database/generated/client/runtime/library").Decimal;
            issueDate: Date;
            dueDate: Date | null;
            stripePaymentLinkUrl: string | null;
            stripePaymentLinkId: string | null;
            paidAt: Date | null;
            voidedAt: Date | null;
        };
    }>;
    create(user: AuthenticatedUser, dto: CreateInvoiceDto): Promise<{
        data: {
            number: string;
            id: string;
            tenantId: string;
            status: import("@sealed/database").$Enums.InvoiceStatus;
            createdAt: Date;
            updatedAt: Date;
            contactId: string;
            publicToken: string;
            lineItems: import("@sealed/database/generated/client/runtime/library").JsonValue;
            subtotal: import("@sealed/database/generated/client/runtime/library").Decimal;
            taxAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            totalAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            currency: string;
            sentAt: Date | null;
            createdByUserId: string;
            agreementId: string;
            amountPaid: import("@sealed/database/generated/client/runtime/library").Decimal;
            issueDate: Date;
            dueDate: Date | null;
            stripePaymentLinkUrl: string | null;
            stripePaymentLinkId: string | null;
            paidAt: Date | null;
            voidedAt: Date | null;
        };
    }>;
    update(user: AuthenticatedUser, id: string, dto: UpdateInvoiceDto): Promise<{
        data: {
            contact: {
                id: string;
                tenantId: string;
                email: string;
                name: string;
                createdAt: Date;
                updatedAt: Date;
                phone: string | null;
                companyName: string | null;
                metadata: import("@sealed/database/generated/client/runtime/library").JsonValue;
            };
            agreement: {
                id: string;
                tenantId: string;
                status: import("@sealed/database").$Enums.AgreementStatus;
                createdAt: Date;
                updatedAt: Date;
                signatureProvider: string | null;
                contactId: string;
                publicToken: string;
                title: string;
                sentAt: Date | null;
                createdByUserId: string;
                proposalId: string;
                body: string;
                signatureRequestId: string | null;
                signedDocumentUrl: string | null;
                signerName: string | null;
                signerEmail: string | null;
                signerIpAddress: string | null;
                signedAt: Date | null;
                declinedAt: Date | null;
            };
            payments: {
                id: string;
                tenantId: string;
                status: import("@sealed/database").$Enums.PaymentStatus;
                createdAt: Date;
                currency: string;
                invoiceId: string;
                provider: import("@sealed/database").$Enums.PaymentProvider;
                providerPaymentId: string | null;
                amount: import("@sealed/database/generated/client/runtime/library").Decimal;
                succeededAt: Date | null;
                failedAt: Date | null;
                refundedAt: Date | null;
                failureReason: string | null;
            }[];
        } & {
            number: string;
            id: string;
            tenantId: string;
            status: import("@sealed/database").$Enums.InvoiceStatus;
            createdAt: Date;
            updatedAt: Date;
            contactId: string;
            publicToken: string;
            lineItems: import("@sealed/database/generated/client/runtime/library").JsonValue;
            subtotal: import("@sealed/database/generated/client/runtime/library").Decimal;
            taxAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            totalAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            currency: string;
            sentAt: Date | null;
            createdByUserId: string;
            agreementId: string;
            amountPaid: import("@sealed/database/generated/client/runtime/library").Decimal;
            issueDate: Date;
            dueDate: Date | null;
            stripePaymentLinkUrl: string | null;
            stripePaymentLinkId: string | null;
            paidAt: Date | null;
            voidedAt: Date | null;
        };
    }>;
    send(user: AuthenticatedUser, id: string): Promise<{
        data: {
            contact: {
                id: string;
                tenantId: string;
                email: string;
                name: string;
                createdAt: Date;
                updatedAt: Date;
                phone: string | null;
                companyName: string | null;
                metadata: import("@sealed/database/generated/client/runtime/library").JsonValue;
            };
            agreement: {
                id: string;
                tenantId: string;
                status: import("@sealed/database").$Enums.AgreementStatus;
                createdAt: Date;
                updatedAt: Date;
                signatureProvider: string | null;
                contactId: string;
                publicToken: string;
                title: string;
                sentAt: Date | null;
                createdByUserId: string;
                proposalId: string;
                body: string;
                signatureRequestId: string | null;
                signedDocumentUrl: string | null;
                signerName: string | null;
                signerEmail: string | null;
                signerIpAddress: string | null;
                signedAt: Date | null;
                declinedAt: Date | null;
            };
            payments: {
                id: string;
                tenantId: string;
                status: import("@sealed/database").$Enums.PaymentStatus;
                createdAt: Date;
                currency: string;
                invoiceId: string;
                provider: import("@sealed/database").$Enums.PaymentProvider;
                providerPaymentId: string | null;
                amount: import("@sealed/database/generated/client/runtime/library").Decimal;
                succeededAt: Date | null;
                failedAt: Date | null;
                refundedAt: Date | null;
                failureReason: string | null;
            }[];
        } & {
            number: string;
            id: string;
            tenantId: string;
            status: import("@sealed/database").$Enums.InvoiceStatus;
            createdAt: Date;
            updatedAt: Date;
            contactId: string;
            publicToken: string;
            lineItems: import("@sealed/database/generated/client/runtime/library").JsonValue;
            subtotal: import("@sealed/database/generated/client/runtime/library").Decimal;
            taxAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            totalAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            currency: string;
            sentAt: Date | null;
            createdByUserId: string;
            agreementId: string;
            amountPaid: import("@sealed/database/generated/client/runtime/library").Decimal;
            issueDate: Date;
            dueDate: Date | null;
            stripePaymentLinkUrl: string | null;
            stripePaymentLinkId: string | null;
            paidAt: Date | null;
            voidedAt: Date | null;
        };
    }>;
}
//# sourceMappingURL=invoices.controller.d.ts.map