import { Prisma } from "@sealed/database";
import { PrismaService } from "../../prisma/prisma.service";
import { CreateInvoiceDto, UpdateInvoiceDto } from "./dto/create-invoice.dto";
export declare class InvoicesService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    findAll(tenantId: string): Prisma.PrismaPromise<({
        contact: {
            id: string;
            tenantId: string;
            email: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            phone: string | null;
            companyName: string | null;
            metadata: Prisma.JsonValue;
        };
        agreement: {
            id: string;
            tenantId: string;
            status: import("@sealed/database").$Enums.AgreementStatus;
            createdAt: Date;
            updatedAt: Date;
            signatureProvider: string | null;
            contactId: string;
            publicToken: string;
            title: string;
            sentAt: Date | null;
            createdByUserId: string;
            proposalId: string;
            body: string;
            signatureRequestId: string | null;
            signedDocumentUrl: string | null;
            signerName: string | null;
            signerEmail: string | null;
            signerIpAddress: string | null;
            signedAt: Date | null;
            declinedAt: Date | null;
        };
    } & {
        number: string;
        id: string;
        tenantId: string;
        status: import("@sealed/database").$Enums.InvoiceStatus;
        createdAt: Date;
        updatedAt: Date;
        contactId: string;
        publicToken: string;
        lineItems: Prisma.JsonValue;
        subtotal: Prisma.Decimal;
        taxAmount: Prisma.Decimal;
        totalAmount: Prisma.Decimal;
        currency: string;
        sentAt: Date | null;
        createdByUserId: string;
        agreementId: string;
        amountPaid: Prisma.Decimal;
        issueDate: Date;
        dueDate: Date | null;
        stripePaymentLinkUrl: string | null;
        stripePaymentLinkId: string | null;
        paidAt: Date | null;
        voidedAt: Date | null;
    })[]>;
    findOne(tenantId: string, id: string): Promise<{
        contact: {
            id: string;
            tenantId: string;
            email: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            phone: string | null;
            companyName: string | null;
            metadata: Prisma.JsonValue;
        };
        agreement: {
            id: string;
            tenantId: string;
            status: import("@sealed/database").$Enums.AgreementStatus;
            createdAt: Date;
            updatedAt: Date;
            signatureProvider: string | null;
            contactId: string;
            publicToken: string;
            title: string;
            sentAt: Date | null;
            createdByUserId: string;
            proposalId: string;
            body: string;
            signatureRequestId: string | null;
            signedDocumentUrl: string | null;
            signerName: string | null;
            signerEmail: string | null;
            signerIpAddress: string | null;
            signedAt: Date | null;
            declinedAt: Date | null;
        };
        payments: {
            id: string;
            tenantId: string;
            status: import("@sealed/database").$Enums.PaymentStatus;
            createdAt: Date;
            currency: string;
            invoiceId: string;
            provider: import("@sealed/database").$Enums.PaymentProvider;
            providerPaymentId: string | null;
            amount: Prisma.Decimal;
            succeededAt: Date | null;
            failedAt: Date | null;
            refundedAt: Date | null;
            failureReason: string | null;
        }[];
    } & {
        number: string;
        id: string;
        tenantId: string;
        status: import("@sealed/database").$Enums.InvoiceStatus;
        createdAt: Date;
        updatedAt: Date;
        contactId: string;
        publicToken: string;
        lineItems: Prisma.JsonValue;
        subtotal: Prisma.Decimal;
        taxAmount: Prisma.Decimal;
        totalAmount: Prisma.Decimal;
        currency: string;
        sentAt: Date | null;
        createdByUserId: string;
        agreementId: string;
        amountPaid: Prisma.Decimal;
        issueDate: Date;
        dueDate: Date | null;
        stripePaymentLinkUrl: string | null;
        stripePaymentLinkId: string | null;
        paidAt: Date | null;
        voidedAt: Date | null;
    }>;
    create(tenantId: string, userId: string, dto: CreateInvoiceDto): Promise<{
        number: string;
        id: string;
        tenantId: string;
        status: import("@sealed/database").$Enums.InvoiceStatus;
        createdAt: Date;
        updatedAt: Date;
        contactId: string;
        publicToken: string;
        lineItems: Prisma.JsonValue;
        subtotal: Prisma.Decimal;
        taxAmount: Prisma.Decimal;
        totalAmount: Prisma.Decimal;
        currency: string;
        sentAt: Date | null;
        createdByUserId: string;
        agreementId: string;
        amountPaid: Prisma.Decimal;
        issueDate: Date;
        dueDate: Date | null;
        stripePaymentLinkUrl: string | null;
        stripePaymentLinkId: string | null;
        paidAt: Date | null;
        voidedAt: Date | null;
    }>;
    update(tenantId: string, userId: string, id: string, dto: UpdateInvoiceDto): Promise<{
        contact: {
            id: string;
            tenantId: string;
            email: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            phone: string | null;
            companyName: string | null;
            metadata: Prisma.JsonValue;
        };
        agreement: {
            id: string;
            tenantId: string;
            status: import("@sealed/database").$Enums.AgreementStatus;
            createdAt: Date;
            updatedAt: Date;
            signatureProvider: string | null;
            contactId: string;
            publicToken: string;
            title: string;
            sentAt: Date | null;
            createdByUserId: string;
            proposalId: string;
            body: string;
            signatureRequestId: string | null;
            signedDocumentUrl: string | null;
            signerName: string | null;
            signerEmail: string | null;
            signerIpAddress: string | null;
            signedAt: Date | null;
            declinedAt: Date | null;
        };
        payments: {
            id: string;
            tenantId: string;
            status: import("@sealed/database").$Enums.PaymentStatus;
            createdAt: Date;
            currency: string;
            invoiceId: string;
            provider: import("@sealed/database").$Enums.PaymentProvider;
            providerPaymentId: string | null;
            amount: Prisma.Decimal;
            succeededAt: Date | null;
            failedAt: Date | null;
            refundedAt: Date | null;
            failureReason: string | null;
        }[];
    } & {
        number: string;
        id: string;
        tenantId: string;
        status: import("@sealed/database").$Enums.InvoiceStatus;
        createdAt: Date;
        updatedAt: Date;
        contactId: string;
        publicToken: string;
        lineItems: Prisma.JsonValue;
        subtotal: Prisma.Decimal;
        taxAmount: Prisma.Decimal;
        totalAmount: Prisma.Decimal;
        currency: string;
        sentAt: Date | null;
        createdByUserId: string;
        agreementId: string;
        amountPaid: Prisma.Decimal;
        issueDate: Date;
        dueDate: Date | null;
        stripePaymentLinkUrl: string | null;
        stripePaymentLinkId: string | null;
        paidAt: Date | null;
        voidedAt: Date | null;
    }>;
    send(tenantId: string, userId: string, id: string): Promise<{
        contact: {
            id: string;
            tenantId: string;
            email: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            phone: string | null;
            companyName: string | null;
            metadata: Prisma.JsonValue;
        };
        agreement: {
            id: string;
            tenantId: string;
            status: import("@sealed/database").$Enums.AgreementStatus;
            createdAt: Date;
            updatedAt: Date;
            signatureProvider: string | null;
            contactId: string;
            publicToken: string;
            title: string;
            sentAt: Date | null;
            createdByUserId: string;
            proposalId: string;
            body: string;
            signatureRequestId: string | null;
            signedDocumentUrl: string | null;
            signerName: string | null;
            signerEmail: string | null;
            signerIpAddress: string | null;
            signedAt: Date | null;
            declinedAt: Date | null;
        };
        payments: {
            id: string;
            tenantId: string;
            status: import("@sealed/database").$Enums.PaymentStatus;
            createdAt: Date;
            currency: string;
            invoiceId: string;
            provider: import("@sealed/database").$Enums.PaymentProvider;
            providerPaymentId: string | null;
            amount: Prisma.Decimal;
            succeededAt: Date | null;
            failedAt: Date | null;
            refundedAt: Date | null;
            failureReason: string | null;
        }[];
    } & {
        number: string;
        id: string;
        tenantId: string;
        status: import("@sealed/database").$Enums.InvoiceStatus;
        createdAt: Date;
        updatedAt: Date;
        contactId: string;
        publicToken: string;
        lineItems: Prisma.JsonValue;
        subtotal: Prisma.Decimal;
        taxAmount: Prisma.Decimal;
        totalAmount: Prisma.Decimal;
        currency: string;
        sentAt: Date | null;
        createdByUserId: string;
        agreementId: string;
        amountPaid: Prisma.Decimal;
        issueDate: Date;
        dueDate: Date | null;
        stripePaymentLinkUrl: string | null;
        stripePaymentLinkId: string | null;
        paidAt: Date | null;
        voidedAt: Date | null;
    }>;
}
//# sourceMappingURL=invoices.service.d.ts.map