import { PrismaService } from "../../prisma/prisma.service";
import { CreateAgreementDto, UpdateAgreementDto } from "./dto/create-agreement.dto";
export declare class AgreementsService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    findAll(tenantId: string): import("@sealed/database").Prisma.PrismaPromise<({
        contact: {
            id: string;
            tenantId: string;
            email: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            phone: string | null;
            companyName: string | null;
            metadata: import("@sealed/database/generated/client/runtime/library").JsonValue;
        };
        proposal: {
            id: string;
            tenantId: string;
            status: import("@sealed/database").$Enums.ProposalStatus;
            createdAt: Date;
            updatedAt: Date;
            contactId: string;
            publicToken: string;
            title: string;
            description: string | null;
            lineItems: import("@sealed/database/generated/client/runtime/library").JsonValue;
            subtotal: import("@sealed/database/generated/client/runtime/library").Decimal;
            taxAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            totalAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            currency: string;
            sentAt: Date | null;
            viewedAt: Date | null;
            respondedAt: Date | null;
            expiresAt: Date | null;
            viewerIpAddress: string | null;
            viewerUserAgent: string | null;
            createdByUserId: string;
        };
    } & {
        id: string;
        tenantId: string;
        status: import("@sealed/database").$Enums.AgreementStatus;
        createdAt: Date;
        updatedAt: Date;
        signatureProvider: string | null;
        contactId: string;
        publicToken: string;
        title: string;
        sentAt: Date | null;
        createdByUserId: string;
        proposalId: string;
        body: string;
        signatureRequestId: string | null;
        signedDocumentUrl: string | null;
        signerName: string | null;
        signerEmail: string | null;
        signerIpAddress: string | null;
        signedAt: Date | null;
        declinedAt: Date | null;
    })[]>;
    findOne(tenantId: string, id: string): Promise<{
        contact: {
            id: string;
            tenantId: string;
            email: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            phone: string | null;
            companyName: string | null;
            metadata: import("@sealed/database/generated/client/runtime/library").JsonValue;
        };
        proposal: {
            id: string;
            tenantId: string;
            status: import("@sealed/database").$Enums.ProposalStatus;
            createdAt: Date;
            updatedAt: Date;
            contactId: string;
            publicToken: string;
            title: string;
            description: string | null;
            lineItems: import("@sealed/database/generated/client/runtime/library").JsonValue;
            subtotal: import("@sealed/database/generated/client/runtime/library").Decimal;
            taxAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            totalAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            currency: string;
            sentAt: Date | null;
            viewedAt: Date | null;
            respondedAt: Date | null;
            expiresAt: Date | null;
            viewerIpAddress: string | null;
            viewerUserAgent: string | null;
            createdByUserId: string;
        };
    } & {
        id: string;
        tenantId: string;
        status: import("@sealed/database").$Enums.AgreementStatus;
        createdAt: Date;
        updatedAt: Date;
        signatureProvider: string | null;
        contactId: string;
        publicToken: string;
        title: string;
        sentAt: Date | null;
        createdByUserId: string;
        proposalId: string;
        body: string;
        signatureRequestId: string | null;
        signedDocumentUrl: string | null;
        signerName: string | null;
        signerEmail: string | null;
        signerIpAddress: string | null;
        signedAt: Date | null;
        declinedAt: Date | null;
    }>;
    create(tenantId: string, userId: string, dto: CreateAgreementDto): Promise<{
        id: string;
        tenantId: string;
        status: import("@sealed/database").$Enums.AgreementStatus;
        createdAt: Date;
        updatedAt: Date;
        signatureProvider: string | null;
        contactId: string;
        publicToken: string;
        title: string;
        sentAt: Date | null;
        createdByUserId: string;
        proposalId: string;
        body: string;
        signatureRequestId: string | null;
        signedDocumentUrl: string | null;
        signerName: string | null;
        signerEmail: string | null;
        signerIpAddress: string | null;
        signedAt: Date | null;
        declinedAt: Date | null;
    }>;
    update(tenantId: string, userId: string, id: string, dto: UpdateAgreementDto): Promise<{
        contact: {
            id: string;
            tenantId: string;
            email: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            phone: string | null;
            companyName: string | null;
            metadata: import("@sealed/database/generated/client/runtime/library").JsonValue;
        };
        proposal: {
            id: string;
            tenantId: string;
            status: import("@sealed/database").$Enums.ProposalStatus;
            createdAt: Date;
            updatedAt: Date;
            contactId: string;
            publicToken: string;
            title: string;
            description: string | null;
            lineItems: import("@sealed/database/generated/client/runtime/library").JsonValue;
            subtotal: import("@sealed/database/generated/client/runtime/library").Decimal;
            taxAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            totalAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            currency: string;
            sentAt: Date | null;
            viewedAt: Date | null;
            respondedAt: Date | null;
            expiresAt: Date | null;
            viewerIpAddress: string | null;
            viewerUserAgent: string | null;
            createdByUserId: string;
        };
    } & {
        id: string;
        tenantId: string;
        status: import("@sealed/database").$Enums.AgreementStatus;
        createdAt: Date;
        updatedAt: Date;
        signatureProvider: string | null;
        contactId: string;
        publicToken: string;
        title: string;
        sentAt: Date | null;
        createdByUserId: string;
        proposalId: string;
        body: string;
        signatureRequestId: string | null;
        signedDocumentUrl: string | null;
        signerName: string | null;
        signerEmail: string | null;
        signerIpAddress: string | null;
        signedAt: Date | null;
        declinedAt: Date | null;
    }>;
    sendForSignature(tenantId: string, userId: string, id: string): Promise<{
        contact: {
            id: string;
            tenantId: string;
            email: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            phone: string | null;
            companyName: string | null;
            metadata: import("@sealed/database/generated/client/runtime/library").JsonValue;
        };
        proposal: {
            id: string;
            tenantId: string;
            status: import("@sealed/database").$Enums.ProposalStatus;
            createdAt: Date;
            updatedAt: Date;
            contactId: string;
            publicToken: string;
            title: string;
            description: string | null;
            lineItems: import("@sealed/database/generated/client/runtime/library").JsonValue;
            subtotal: import("@sealed/database/generated/client/runtime/library").Decimal;
            taxAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            totalAmount: import("@sealed/database/generated/client/runtime/library").Decimal;
            currency: string;
            sentAt: Date | null;
            viewedAt: Date | null;
            respondedAt: Date | null;
            expiresAt: Date | null;
            viewerIpAddress: string | null;
            viewerUserAgent: string | null;
            createdByUserId: string;
        };
    } & {
        id: string;
        tenantId: string;
        status: import("@sealed/database").$Enums.AgreementStatus;
        createdAt: Date;
        updatedAt: Date;
        signatureProvider: string | null;
        contactId: string;
        publicToken: string;
        title: string;
        sentAt: Date | null;
        createdByUserId: string;
        proposalId: string;
        body: string;
        signatureRequestId: string | null;
        signedDocumentUrl: string | null;
        signerName: string | null;
        signerEmail: string | null;
        signerIpAddress: string | null;
        signedAt: Date | null;
        declinedAt: Date | null;
    }>;
}
//# sourceMappingURL=agreements.service.d.ts.map